version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Database
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/shopify_app
      - NODE_ENV=production
      # Shopify App Variables
      - SHOPIFY_APP_URL=https://localhost:3000
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_API_SECRET=${SHOPIFY_API_SECRET}
      - SCOPES=${SCOPES}
      - APP_NAME=${APP_NAME}
    depends_on:
      - db
    env_file:
      - .env  # Add this line to ensure the .env file is loaded


  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopify_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
